SET @user_num = (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / @user_num, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS S
    JOIN USER_INFO AS U ON S.USER_ID = U.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
