SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES
    JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;
